# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(503, 609)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 140, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 140, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 140, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        Window.setPalette(palette)
        Window.setLayoutDirection(QtCore.Qt.LeftToRight)
        Window.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")
        self.avatar = QtWidgets.QLabel(self.centralwidget)
        self.avatar.setGeometry(QtCore.QRect(20, 10, 100, 100))
        self.avatar.setMinimumSize(QtCore.QSize(100, 100))
        self.avatar.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Sarpanch Medium")
        font.setPointSize(10)
        self.avatar.setFont(font)
        self.avatar.setAutoFillBackground(True)
        self.avatar.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.avatar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.avatar.setAlignment(QtCore.Qt.AlignCenter)
        self.avatar.setObjectName("avatar")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(9, 504, 480, 70))
        self.splitter.setMinimumSize(QtCore.QSize(480, 70))
        self.splitter.setMaximumSize(QtCore.QSize(484, 70))
        self.splitter.setAutoFillBackground(True)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.splitter.setLineWidth(1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.InputText = QtWidgets.QTextEdit(self.splitter)
        self.InputText.setMinimumSize(QtCore.QSize(0, 68))
        self.InputText.setMaximumSize(QtCore.QSize(409, 71))
        font = QtGui.QFont()
        font.setFamily("Sarpanch")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.InputText.setFont(font)
        self.InputText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.InputText.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.InputText.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.InputText.setDocumentTitle("")
        self.InputText.setTabStopWidth(80)
        self.InputText.setCursorWidth(2)
        self.InputText.setObjectName("InputText")
        self.ButtonSend = QtWidgets.QPushButton(self.splitter)
        self.ButtonSend.setEnabled(True)
        self.ButtonSend.setMinimumSize(QtCore.QSize(71, 68))
        self.ButtonSend.setMaximumSize(QtCore.QSize(71, 70))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.ButtonSend.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(13)
        self.ButtonSend.setFont(font)
        self.ButtonSend.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ButtonSend.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ButtonSend.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ButtonSend.setAutoFillBackground(True)
        self.ButtonSend.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/paper-plane.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ButtonSend.setIcon(icon)
        self.ButtonSend.setIconSize(QtCore.QSize(65, 65))
        self.ButtonSend.setCheckable(False)
        self.ButtonSend.setAutoRepeat(False)
        self.ButtonSend.setObjectName("ButtonSend")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(9, 115, 480, 343))
        self.splitter_2.setMinimumSize(QtCore.QSize(480, 0))
        self.splitter_2.setMaximumSize(QtCore.QSize(16777215, 345))
        self.splitter_2.setAutoFillBackground(True)
        self.splitter_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.splitter_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_2)
        self.splitter_6.setMinimumSize(QtCore.QSize(125, 345))
        self.splitter_6.setMaximumSize(QtCore.QSize(16777215, 330))
        self.splitter_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.contacts = QtWidgets.QLabel(self.splitter_6)
        self.contacts.setMinimumSize(QtCore.QSize(0, 25))
        self.contacts.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Sarpanch Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.contacts.setFont(font)
        self.contacts.setFocusPolicy(QtCore.Qt.NoFocus)
        self.contacts.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.contacts.setAutoFillBackground(True)
        self.contacts.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.contacts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contacts.setTextFormat(QtCore.Qt.AutoText)
        self.contacts.setScaledContents(False)
        self.contacts.setAlignment(QtCore.Qt.AlignCenter)
        self.contacts.setWordWrap(False)
        self.contacts.setObjectName("contacts")
        self.listWidget = QtWidgets.QListWidget(self.splitter_6)
        self.listWidget.setMinimumSize(QtCore.QSize(147, 300))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("Sarpanch")
        font.setPointSize(10)
        self.listWidget.setFont(font)
        self.listWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget.setObjectName("listWidget")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_2)
        self.splitter_5.setMinimumSize(QtCore.QSize(250, 345))
        self.splitter_5.setMaximumSize(QtCore.QSize(300, 330))
        self.splitter_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.chat = QtWidgets.QLabel(self.splitter_5)
        self.chat.setMinimumSize(QtCore.QSize(235, 25))
        self.chat.setMaximumSize(QtCore.QSize(360, 25))
        font = QtGui.QFont()
        font.setFamily("Sarpanch Medium")
        font.setPointSize(12)
        self.chat.setFont(font)
        self.chat.setAutoFillBackground(True)
        self.chat.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.chat.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat.setAlignment(QtCore.Qt.AlignCenter)
        self.chat.setObjectName("chat")
        self.storyMessage = QtWidgets.QListWidget(self.splitter_5)
        self.storyMessage.setMinimumSize(QtCore.QSize(248, 288))
        self.storyMessage.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Sarpanch")
        font.setPointSize(10)
        self.storyMessage.setFont(font)
        self.storyMessage.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.storyMessage.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.storyMessage.setObjectName("storyMessage")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(9, 464, 476, 37))
        self.splitter_3.setMaximumSize(QtCore.QSize(476, 37))
        self.splitter_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.boldBt = QtWidgets.QPushButton(self.splitter_3)
        self.boldBt.setMinimumSize(QtCore.QSize(32, 32))
        self.boldBt.setMaximumSize(QtCore.QSize(32, 32))
        self.boldBt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.boldBt.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/b.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boldBt.setIcon(icon1)
        self.boldBt.setIconSize(QtCore.QSize(32, 32))
        self.boldBt.setObjectName("boldBt")
        self.italicBt = QtWidgets.QPushButton(self.splitter_3)
        self.italicBt.setMinimumSize(QtCore.QSize(32, 32))
        self.italicBt.setMaximumSize(QtCore.QSize(32, 32))
        self.italicBt.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/i.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.italicBt.setIcon(icon2)
        self.italicBt.setIconSize(QtCore.QSize(32, 32))
        self.italicBt.setObjectName("italicBt")
        self.underlinedBt = QtWidgets.QPushButton(self.splitter_3)
        self.underlinedBt.setMinimumSize(QtCore.QSize(32, 32))
        self.underlinedBt.setMaximumSize(QtCore.QSize(32, 32))
        self.underlinedBt.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/u.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.underlinedBt.setIcon(icon3)
        self.underlinedBt.setIconSize(QtCore.QSize(32, 32))
        self.underlinedBt.setObjectName("underlinedBt")
        self.smileBt = QtWidgets.QPushButton(self.splitter_3)
        self.smileBt.setMinimumSize(QtCore.QSize(32, 32))
        self.smileBt.setMaximumSize(QtCore.QSize(32, 32))
        self.smileBt.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/smile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.smileBt.setIcon(icon4)
        self.smileBt.setIconSize(QtCore.QSize(26, 26))
        self.smileBt.setObjectName("smileBt")
        self.tongueBt = QtWidgets.QPushButton(self.splitter_3)
        self.tongueBt.setMinimumSize(QtCore.QSize(32, 32))
        self.tongueBt.setMaximumSize(QtCore.QSize(32, 32))
        self.tongueBt.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/tongue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tongueBt.setIcon(icon5)
        self.tongueBt.setIconSize(QtCore.QSize(26, 26))
        self.tongueBt.setObjectName("tongueBt")
        self.winkBt = QtWidgets.QPushButton(self.splitter_3)
        self.winkBt.setMinimumSize(QtCore.QSize(32, 32))
        self.winkBt.setMaximumSize(QtCore.QSize(32, 32))
        self.winkBt.setAutoFillBackground(False)
        self.winkBt.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/wink.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.winkBt.setIcon(icon6)
        self.winkBt.setIconSize(QtCore.QSize(26, 26))
        self.winkBt.setObjectName("winkBt")
        self.suspectBt = QtWidgets.QPushButton(self.splitter_3)
        self.suspectBt.setMinimumSize(QtCore.QSize(32, 32))
        self.suspectBt.setMaximumSize(QtCore.QSize(32, 32))
        self.suspectBt.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/suspect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.suspectBt.setIcon(icon7)
        self.suspectBt.setIconSize(QtCore.QSize(26, 26))
        self.suspectBt.setObjectName("suspectBt")
        self.indifferentBt = QtWidgets.QPushButton(self.splitter_3)
        self.indifferentBt.setMinimumSize(QtCore.QSize(32, 32))
        self.indifferentBt.setMaximumSize(QtCore.QSize(32, 32))
        self.indifferentBt.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/indifferent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.indifferentBt.setIcon(icon8)
        self.indifferentBt.setIconSize(QtCore.QSize(26, 26))
        self.indifferentBt.setObjectName("indifferentBt")
        self.kissBt = QtWidgets.QPushButton(self.splitter_3)
        self.kissBt.setMinimumSize(QtCore.QSize(32, 32))
        self.kissBt.setMaximumSize(QtCore.QSize(32, 32))
        self.kissBt.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/kiss.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kissBt.setIcon(icon9)
        self.kissBt.setIconSize(QtCore.QSize(26, 26))
        self.kissBt.setObjectName("kissBt")
        self.deadBt = QtWidgets.QPushButton(self.splitter_3)
        self.deadBt.setMinimumSize(QtCore.QSize(32, 32))
        self.deadBt.setMaximumSize(QtCore.QSize(32, 32))
        self.deadBt.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/dead.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deadBt.setIcon(icon10)
        self.deadBt.setIconSize(QtCore.QSize(26, 26))
        self.deadBt.setObjectName("deadBt")
        self.flowerBt = QtWidgets.QPushButton(self.splitter_3)
        self.flowerBt.setMinimumSize(QtCore.QSize(32, 32))
        self.flowerBt.setMaximumSize(QtCore.QSize(32, 32))
        self.flowerBt.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/flower.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flowerBt.setIcon(icon11)
        self.flowerBt.setIconSize(QtCore.QSize(25, 25))
        self.flowerBt.setObjectName("flowerBt")
        self.flowersBt = QtWidgets.QPushButton(self.splitter_3)
        self.flowersBt.setMinimumSize(QtCore.QSize(32, 32))
        self.flowersBt.setMaximumSize(QtCore.QSize(32, 32))
        self.flowersBt.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/flowers.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flowersBt.setIcon(icon12)
        self.flowersBt.setIconSize(QtCore.QSize(25, 25))
        self.flowersBt.setObjectName("flowersBt")
        self.chocolateBt = QtWidgets.QPushButton(self.splitter_3)
        self.chocolateBt.setMinimumSize(QtCore.QSize(32, 32))
        self.chocolateBt.setMaximumSize(QtCore.QSize(32, 32))
        self.chocolateBt.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/chocolate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chocolateBt.setIcon(icon13)
        self.chocolateBt.setIconSize(QtCore.QSize(25, 25))
        self.chocolateBt.setObjectName("chocolateBt")
        self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_4.setGeometry(QtCore.QRect(142, 30, 327, 50))
        self.splitter_4.setMaximumSize(QtCore.QSize(410, 50))
        self.splitter_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.ButtonAdd = QtWidgets.QPushButton(self.splitter_4)
        self.ButtonAdd.setMinimumSize(QtCore.QSize(50, 50))
        self.ButtonAdd.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Sarpanch Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ButtonAdd.setFont(font)
        self.ButtonAdd.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ButtonAdd.setIcon(icon14)
        self.ButtonAdd.setIconSize(QtCore.QSize(40, 40))
        self.ButtonAdd.setObjectName("ButtonAdd")
        self.textEdit = QtWidgets.QTextEdit(self.splitter_4)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.textEdit.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Sarpanch")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit.setAutoFillBackground(True)
        self.textEdit.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textEdit.setMidLineWidth(0)
        self.textEdit.setTabChangesFocus(False)
        self.textEdit.setDocumentTitle("")
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit.setLineWrapColumnOrWidth(0)
        self.textEdit.setOverwriteMode(False)
        self.textEdit.setTabStopWidth(80)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextEditorInteraction)
        self.textEdit.setPlaceholderText("")
        self.textEdit.setObjectName("textEdit")
        self.ButtonDelete = QtWidgets.QPushButton(self.splitter_4)
        self.ButtonDelete.setMinimumSize(QtCore.QSize(50, 50))
        self.ButtonDelete.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Sarpanch Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ButtonDelete.setFont(font)
        self.ButtonDelete.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ButtonDelete.setAutoFillBackground(True)
        self.ButtonDelete.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ButtonDelete.setIcon(icon15)
        self.ButtonDelete.setIconSize(QtCore.QSize(40, 40))
        self.ButtonDelete.setAutoDefault(False)
        self.ButtonDelete.setObjectName("ButtonDelete")
        Window.setCentralWidget(self.centralwidget)
        self.File = QtWidgets.QMenuBar(Window)
        self.File.setGeometry(QtCore.QRect(0, 0, 503, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 232, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 140, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 232, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 232, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 140, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 232, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 232, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 140, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.File.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Sarpanch Medium")
        font.setPointSize(8)
        self.File.setFont(font)
        self.File.setDefaultUp(False)
        self.File.setNativeMenuBar(True)
        self.File.setObjectName("File")
        Window.setMenuBar(self.File)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Converse"))
        self.avatar.setText(_translate("Window", "avatar"))
        self.InputText.setPlaceholderText(_translate("Window", "message:"))
        self.contacts.setText(_translate("Window", "CONTACTS"))
        self.chat.setText(_translate("Window", "CHAT"))

